- name: Disable advserviceHighCpu feature flag
  hosts: all
  become: true

  tasks:
    - name: Edit the ConfigMap to disable advserviceHighCpu
      command: kubectl edit configmap <configmap_name> -n <namespace>
      args:
        executable: /bin/bash
      register: configmap_edit_output

    - name: Verify the flag's value has been updated
      command: kubectl get configmap <configmap_name> -n <namespace> -o jsonpath='{.data.advserviceHighCpu}'
      register: flag_value

    - name: Display the updated flag value
      debug:
        msg: "advserviceHighCpu flag value is {{ flag_value.stdout }}"