- name: Update advserviceHighCpu flag to false in ConfigMap using k8s modules and extra_vars for namespace and configmap name
  hosts: all
  tasks:
    - name: Obtain access token
      k8s_auth:
        host: "{{ k8s_api_server }}"
        validate_certs: no
        username: "{{ k8s_user }}"
        password: "{{ k8s_password }}"
      register: k8s_auth_results
      
    - name: patch configmap to set advserviceHighCpu feature flag to false
      k8s:
        api_key: "{{k8s_auth_results.k8s_auth.api_key}}"
        state: present
        definition:
          kind: ConfigMap
          metadata:
            name: "{{ configmap_name }}"
            namespace: "{{ namespace }}"
          data:
            advserviceHighCpu: "false"
            
    - name: Verify the value of advserviceHighCpu feature flag
      k8s_info:
        api_key: "{{k8s_auth_results.k8s_auth.api_key}}"
        kind: ConfigMap
        namespace: "{{ namespace }}"
        name: "{{ configmap_name }}"
      register: configmap_info

    - name: Display the value of adservicecpuhigh feature flag
      debug:
        msg: "adservicecpuhigh feature flag value is {{ configmap_info.resources[0].data.advserviceHighCpu }}"
