---
- name: Update a ConfigMap value in Kubernetes
  hosts: all
  gather_facts: no
  tasks:
    - name: Update ConfigMap value to false
      ansible.builtin.command: >
        kubectl patch configmap {{ configmap_name }}
        -n {{ namespace }}
        --type merge
        -p '{"data": {"{{ key_name }}": "false"}}'
      register: patch_result

    - name: Show patch result
      ansible.builtin.debug:
        var: patch_result.stdout

